name: Wardrobe
author: Inamine
website: discord.inamine.me
description: Select Colored Armor! Made for Gang Wars by Sooshio
main: me.inamine.wardrobes.Main.Main
version: 1,0
api-version: 1.13
permissions:
  wardrobe.*:
    default: op
  wardrobe.reload:
    default: op
  wardrobe.open:
    default: true
commands:
    wardrobe:
        description: Opens Wardrobe selection
        usage: /<command> [reload]